# frozen_string_literal: true

require "yaml"

module Nabu
  # The language desk reference (P18-4) — the merged read over the two
  # temperatures of per-language data:
  #
  # - DERIVED (catalog, migration 011): the language_names census — what
  #   kaikki's descendants nodes call each lang_code, counted raw per
  #   dictionary by DictionaryLoader. This class reduces it at read time:
  #   plausibility filter (drop "unknown", "… script" wrapper nodes, and
  #   free-text fragments that don't start with a capital), then the mode
  #   over the summed counts. Regenerated by any rebuild/parse-only resync.
  # - ACCUMULATED (ledger, ledger migration 004): language_notes — curated
  #   context that is NOT a function of canonical/. Append-only; the latest
  #   note per (lang_code, kind) wins. Kinds shipped: "name" (beats the
  #   census), "family", "context". Family-level notes ride the family
  #   PREFIX as their lang_code ("zle" for zle-*).
  #
  # Both handles are optional and both tables are guarded (a catalog before
  # migration 011, a ledger before 004, or no db at all reads as "no data" —
  # the honest degradation every read surface here practices).
  class Languages
    SEED_PATH = File.join(File.expand_path("../..", __dir__), "config", "languages.yml")
    SEED_SOURCE = "seed:config/languages.yml"
    NOTE_KINDS = %w[name family context].freeze

    Family = Data.define(:code, :name, :context)
    SeedReport = Data.define(:appended, :unchanged)

    def initialize(catalog: nil, ledger: nil)
      @catalog = catalog
      @ledger = ledger
    end

    # Curated name > census mode > nil.
    def name(code)
      note(code, "name") || census_name(code)
    end

    def context(code) = note(code, "context")
    def family(code) = note(code, "family")

    # P18-5: the accretion kinds beyond the shipped three — programmatic
    # writers ("iecor" today) file under their own kind, so they can never
    # supersede curated name/family/context. Latest body per kind, kinds
    # sorted (deterministic card order); {} without a ledger or table.
    def extra_notes(code)
      return {} unless notes?

      @ledger[:language_notes]
        .where(lang_code: code.to_s)
        .exclude(kind: NOTE_KINDS)
        .order(:kind, :id)
        .to_h { |row| [row[:kind], row[:body]] } # duplicate kinds: the latest id wins
    end

    def curated?(code)
      return false unless notes?

      !@ledger[:language_notes].where(lang_code: code.to_s).empty?
    end

    # The family fallback for a hyphenated etymology code: "zle-ort" looks
    # up the notes filed under "zle" (Wiktionary's own family-code
    # namespace). nil when the prefix carries no notes — no guessing.
    def family_fallback(code)
      prefix = code.to_s.split("-").first
      return nil if prefix.nil? || prefix.empty? || prefix == code.to_s

      fam_name = note(prefix, "name")
      fam_context = note(prefix, "context")
      return nil unless fam_name || fam_context

      Family.new(code: prefix, name: fam_name, context: fam_context)
    end

    # -- census (derived) ----------------------------------------------------------

    # The read-side reduction of the raw census: sum occurrences across
    # dictionaries per (code, name), drop implausible names, take the mode.
    def census_name(code)
      return nil unless census?

      rows = @catalog[:language_names]
             .where(lang_code: code.to_s)
             .select_group(:name)
             .select_append { sum(:occurrences).as(:total) }
             .all
      best = rows.select { |row| self.class.plausible_name?(row[:name]) }
                 .max_by { |row| row[:total] }
      best && best[:name]
    end

    # The plausibility filter (census 2026-07-14 over the eight live kaikki
    # extracts): "unknown" placeholder nodes, script wrapper nodes ("Old
    # Cyrillic script" outnumbers "Old Church Slavonic" under cu), and
    # free-text fragments (") dialect words", "→ Baltic German") — all real
    # upstream noise the mode must not crown. Filtering happens at READ so a
    # rule change never needs a reparse.
    def self.plausible_name?(name)
      text = name.to_s
      return false if text.empty? || text == "unknown"
      return false if text.match?(/script\z/i)

      text.match?(/\A\p{Lu}/)
    end

    # -- seed (accumulated) --------------------------------------------------------

    # Load config/languages.yml (curation reviewable in git) into the
    # ledger's language_notes, idempotently: a note is appended ONLY when the
    # latest stored body for (code, kind) differs — re-running is a no-op,
    # editing the YAML and re-seeding appends a superseding note. The update
    # path for future accretion is exactly this reload (plus, later, a write
    # command / agent accretions — future work, not built).
    def self.seed!(ledger:, path: SEED_PATH, now: Time.now)
      data = YAML.safe_load_file(path) || {}
      appended = 0
      unchanged = 0
      ledger.transaction do
        seed_entries(data).each do |code, kind, body|
          if latest_body(ledger, code, kind) == body
            unchanged += 1
          else
            ledger[:language_notes].insert(lang_code: code, kind: kind, body: body,
                                           source: SEED_SOURCE, created_at: now)
            appended += 1
          end
        end
      end
      SeedReport.new(appended: appended, unchanged: unchanged)
    end

    def self.seed_entries(data)
      entries = %w[languages families].flat_map do |section|
        (data[section] || {}).flat_map do |code, fields|
          NOTE_KINDS.filter_map do |kind|
            body = fields[kind].to_s.strip
            [code.to_s, kind, body] unless body.empty?
          end
        end
      end
      # A code in BOTH sections would ping-pong supersessions on every
      # re-seed (grc nearly did) — refuse loudly instead.
      duplicates = entries.group_by { |code, kind, _| [code, kind] }.select { |_, group| group.size > 1 }
      unless duplicates.empty?
        raise Nabu::Error, "languages.yml: duplicate note(s) for " \
                           "#{duplicates.keys.map { |code, kind| "#{code}/#{kind}" }.join(', ')} " \
                           "— a code may appear in one section only"
      end
      entries
    end

    def self.latest_body(ledger, code, kind)
      ledger[:language_notes].where(lang_code: code, kind: kind)
                             .order(Sequel.desc(:id)).get(:body)
    end

    private

    def note(code, kind)
      return nil unless notes?

      @ledger[:language_notes]
        .where(lang_code: code.to_s, kind: kind)
        .order(Sequel.desc(:id))
        .get(:body)
    end

    def census?
      !@catalog.nil? && @catalog.table_exists?(:language_names)
    end

    def notes?
      !@ledger.nil? && @ledger.table_exists?(:language_notes)
    end
  end
end
