# frozen_string_literal: true

require "test_helper"
require "yaml"

module Site
  # The site-data drift guard (P58 rider, owner commission — "no more
  # chasing stale info every phase-end"): site/_data/desks.yml is a pure
  # projection of the registries, so this test regenerates it in memory
  # and FAILS THE SUITE the day the committed copy goes stale — minting a
  # new research desk turns the suite red until `rake site:data` runs.
  # census.yml is dated live data: its SHAPE is pinned here, its values
  # are free to move with the corpus.
  class SiteDataTest < Minitest::Test
    ROOT = Nabu::Config::PROJECT_ROOT
    DATA_DIR = File.join(ROOT, "site", "_data")

    def registry
      @registry ||= Nabu::SourceRegistry.load(File.join(ROOT, "config", "sources.yml"))
    end

    def test_committed_desks_data_matches_the_registry_projection
      committed = YAML.safe_load_file(File.join(DATA_DIR, "desks.yml"))
      fresh = Nabu::Ops::SiteData.new(registry: registry, data_dir: DATA_DIR).desks
      assert_equal fresh, committed,
                   "site/_data/desks.yml is stale against config/axes.yml + config/sources.yml — " \
                   "run `rake site:data` (a new desk is invisible on the home page until you do)"
    end

    def test_census_data_carries_every_key_the_site_prose_cites
      census = YAML.safe_load_file(File.join(DATA_DIR, "census.yml"))
      %w[as_of documents documents_display passages passages_display language_codes
         top_languages dictionary_entries_display dictionary_shelves
         gold_lemmas_m silver_lemmas_m gold_languages desks].each do |key|
        assert census.key?(key), "census.yml lost the #{key} key the site prose cites"
      end
      assert_match(/\A\d{1,2} \w+ \d{4}\z/, census.fetch("as_of"), "as_of must be a dated stamp")
      refute_empty census.fetch("top_languages")
    end

    def test_generated_files_carry_the_do_not_hand_edit_marker
      %w[desks.yml census.yml].each do |name|
        first_line = File.open(File.join(DATA_DIR, name), &:readline)
        assert_match(/GENERATED by `rake site:data`/, first_line)
      end
    end

    # The home page must READ the data, not carry a hand list — the exact
    # regression this rider exists to prevent (the Tibetologist was missing
    # from a hand-maintained desk list while the page claimed the full count).
    def test_the_home_page_reads_desks_and_census_through_liquid
      index = File.read(File.join(ROOT, "site", "index.md"))
      assert_includes index, "site.data.desks", "the desk list must loop over site.data.desks"
      assert_includes index, "site.data.census", "the holdings numbers must come from site.data.census"
      refute_match(/^- \*\*\[The Classicist\]/, index,
                   "no hand-maintained desk list may return to index.md")
    end

    # -- the formatting helpers ------------------------------------------------

    def test_persona_splits_at_the_em_dash
      name, blurb = Nabu::Ops::SiteData.split_persona(
        "The Classicist — Greek and Latin letters read whole, Homer to the late grammarians."
      )
      assert_equal "The Classicist", name
      assert_equal "Greek and Latin letters read whole, Homer to the late grammarians", blurb
    end

    def test_number_formatting
      assert_equal "975,074", Nabu::Ops::SiteData.commas(975_074)
      assert_equal "68,408,109", Nabu::Ops::SiteData.commas(68_408_109)
      assert_equal "512", Nabu::Ops::SiteData.commas(512)
      assert_equal "33.3", Nabu::Ops::SiteData.millions(33_294_700)
      assert_equal "3.0", Nabu::Ops::SiteData.millions(3_042_208)
    end
  end
end
