# frozen_string_literal: true

require "test_helper"

module Site
  # The prose single-source-of-truth guard (owner commission 2026-08-28 —
  # "all the numbers/dates need to refer to a single source of truth; the
  # prose must use it, not hardcode"). site/_data/census.yml is the SSOT,
  # regenerated from the live catalog by `rake site:data`; every site page
  # that states a library-wide headline figure must READ it through Liquid
  # (`{{ site.data.census.* }}`), never copy the number into prose where it
  # rots. This test turns that rule into a red/green gate: it fails the day
  # a page hardcodes a headline total or lets a known-stale figure return.
  #
  # SCOPE: the shared, drifting HEADLINE figures — library-wide document /
  # passage / code / source / dictionary / lemma totals and the desk count,
  # plus their as-of date. Per-source and per-section detail numbers (a
  # single corpus's counts in a table row, one dictionary's entry count, the
  # place-program's own census) are page-local facts, out of this guard's
  # scope; the news archive (site/news/_posts) is a dated historical record
  # and is never scanned.
  class SiteProseSsotTest < Minitest::Test
    ROOT = Nabu::Config::PROJECT_ROOT
    SITE = File.join(ROOT, "site")

    # Every page that states a library-wide headline figure must read the
    # census SSOT rather than carry the number in prose.
    SSOT_PAGES = %w[
      index languages library faq tools sources examples about quickstart places
    ].freeze

    # The pre-SSOT values (and the spelled-out desk phrasings) this migration
    # removed. Their return means a page was hand-edited with a stale copy
    # instead of the Liquid field — exactly the drift the SSOT ends.
    STALE_LITERALS = [
      "975,074",          # old document total
      "68,408,109",       # old passage total
      "68.4 million",     # old passage total, prose form
      "1,407,706",        # old dictionary-entry total
      "1,407,280",        # old dictionary-entry total (variant)
      "122 language codes", # old code count
      "thirty-seven languages", # old gold-lemma language count
      "twenty-three [research desks]",
      "twenty-three [research axes]",
      "twenty-three scholarly hats",
      "all twenty-three"
    ].freeze

    # Pure-headline pages whose only million-scale totals ARE the SSOT
    # figures — so a comma-grouped 7-plus-digit literal outside a fenced
    # code block means a total was hardcoded instead of rendered.
    STRICT_PAGES = %w[index languages about quickstart].freeze
    MILLION_LITERAL = /\b\d{1,3}(?:,\d{3}){2,}\b/

    def page(name) = File.read(File.join(SITE, "#{name}.md"))

    def test_headline_pages_read_the_census_ssot
      SSOT_PAGES.each do |name|
        assert_includes page(name), "site.data.census",
                        "site/#{name}.md states a headline figure but does not read it from the census " \
                        "SSOT — render it via {{ site.data.census.* }} (regenerated by `rake site:data`), " \
                        "never hardcode."
      end
    end

    def test_no_page_carries_a_known_stale_headline_literal
      Dir.glob(File.join(SITE, "*.md")).each do |path|
        body = File.read(path)
        STALE_LITERALS.each do |literal|
          refute_includes body, literal,
                          "#{File.basename(path)} carries the pre-SSOT literal #{literal.inspect} — " \
                          "the headline figures now come from site/_data/census.yml through Liquid; " \
                          "replace the hardcoded value with its {{ site.data.census.* }} field."
        end
      end
    end

    def test_pure_headline_pages_do_not_hardcode_million_scale_totals
      STRICT_PAGES.each do |name|
        prose = page(name).gsub(/```.*?```/m, "") # code blocks show illustrative CLI output
        hits = prose.scan(MILLION_LITERAL)
        assert_empty hits,
                     "site/#{name}.md hardcodes a million-scale total #{hits.inspect} outside a code block — " \
                     "on a pure-headline page every such figure must render from the census SSOT."
      end
    end
  end
end
