# frozen_string_literal: true

# P19-1: the DERIVED per-language knowledge records — what the catalog knows
# about each language code, parsed from the canonical/local-language dossier
# files (one Markdown dossier per code; architecture §16). This is the
# REHOMING of P18-4's ledger language_notes: authored knowledge now lives as
# FILES under canonical/ (the permanent asset), and this table is nothing but
# its index — temperature 1, dropped and regenerated by `nabu rebuild`,
# replaced per code at every local-language sync. The ledger table
# (ledger_migrate/004) stays readable as a transition fallback until the
# owner-fired export migrates its content into dossiers; a later packet drops
# it after parity is verified.
#
# One row per (lang_code, kind) as the dossier currently states it — the
# dossier IS the latest, so no supersession bookkeeping lives here (git and
# the section provenance headers carry history). `kind` is the P18-4 open
# vocabulary unchanged (name/family/context, witness:<slug>, iecor, plus any
# front-matter extras like period/scripts); `source` is the per-record
# provenance carried over from the section header ("iecor", "liv") or
# "dossier" for owner-curated front-matter/prose lanes.
Sequel.migration do
  change do
    create_table(:language_records) do
      primary_key :id
      String :lang_code, null: false
      String :kind, null: false
      String :body, text: true, null: false
      String :source, null: false

      index %i[lang_code kind]
    end
  end
end
