# frozen_string_literal: true

# P24-1: the DERIVED owner-note index — what the catalog knows about the
# owner's annotations, parsed from the canonical/local-notes topic files
# (one YAML list of note records per topic; architecture §16). Canonical-
# memory doctrine: the notes live as FILES under canonical/, this table is
# nothing but their index — temperature 1, dropped and regenerated by
# `nabu rebuild`, replaced per topic at every local-notes sync.
#
# One row per note record as its topic file currently states it. `urn` is
# ANY urn the corpus knows (document, passage, range, dictionary entry —
# resolution is the write gateway's job; a --force note on a not-yet-held
# urn sits here too, flagged dangling at render). `tags` is a JSON array
# (NULL when untagged); `added` an ISO date string; `provenance` names the
# canonical file of record ("local-notes/<topic>.yml").
Sequel.migration do
  change do
    create_table(:urn_notes) do
      primary_key :id
      String :urn, null: false
      String :note, text: true, null: false
      String :topic, null: false
      String :tags, text: true
      String :added, null: false
      String :provenance, null: false

      index :urn
      index :topic
    end
  end
end
