# frozen_string_literal: true

# P24-0: the DERIVED per-source knowledge records — what the catalog knows
# about each registered source, parsed from the canonical/local-source
# dossier files (one Markdown dossier per source slug; architecture §16).
# language_records' twin at the SOURCE grain: authored source knowledge
# lives as FILES under canonical/ (the permanent asset), and this table is
# nothing but its index — temperature 1, dropped and regenerated by
# `nabu rebuild`, replaced per slug at every local-source sync.
#
# One row per (slug, kind) as the dossier currently states it — the dossier
# IS the latest, so no supersession bookkeeping lives here (git and the
# section provenance headers carry history). `kind` is an open vocabulary:
# description (the load-bearing 1–3 sentence content description), theme,
# key_work, note (the curated prose body), front-matter extras, and
# writer-owned accretion kinds (witness:<slug>). `provenance` is "dossier"
# for owner-curated lanes or the section header's source for accretions.
Sequel.migration do
  change do
    create_table(:source_records) do
      primary_key :id
      String :slug, null: false
      String :kind, null: false
      String :body, text: true, null: false
      String :provenance, null: false

      index %i[slug kind]
    end
  end
end
