# frozen_string_literal: true

# P45-6: the derived Pleiades place index — the gazetteer dump projected into
# catalog tables at LOAD time (sync/rebuild, Store::PlaceIndex) so the read
# surfaces (`nabu place`, the `nabu show` findspot line, MCP nabu_place) stop
# re-parsing the 129 MB JSON dump per invocation (~3 s / ~3.9 GB peak RSS, the
# accepted P44-2 v1 cost this table retires). The source_stats posture
# (migration 019): a derived table in catalog.sqlite3 with the full
# rebuildability contract — wholesale-derived from canonical/pleiades bytes,
# dropped and regenerated by `nabu rebuild`. Only the display facts ride here
# (title, representative point, place types, attested time periods — a few
# hundred bytes per place, ~42k places); the dump's bulky per-place payload
# (names, locations, connections, contributors) stays in canonical, per the
# no-bulky-payloads rule.
#
# Two tables, deliberately surrogate-key-free so two derivations of the same
# dump are literally row-identical (the idempotency test pins this):
#
# - place_index: one row per place, keyed by the upstream pleiades_id (the
#   stable join key the parsers capture); `position` preserves dump order
#   (titled() returns homonyms in dump order, the pinned v1 semantics).
# - place_index_names: the exact-match keys `titled` answers from — the whole
#   title plus each "/"-separated variant segment (P44-3), Unicode-case-folded
#   IN RUBY at derive time (Nabu::Pleiades.title_keys). Folding in Ruby, not
#   SQL, is the point: SQLite's lower() is ASCII-only, and the v1 resolver's
#   casecmp? semantics are Unicode-honest ("ἈΘΗΝΑΙ" must keep matching).
#
# NO backfill here (unlike 019): readers feature-detect a POPULATED index
# (Store::PlaceIndex.populated?) and fall back to the v1 dump path until the
# first post-migration `nabu sync pleiades` or `nabu rebuild` derives it — an
# empty table can never read as an empty gazetteer.
Sequel.migration do
  up do
    create_table(:place_index) do
      String :pleiades_id, primary_key: true
      String :title
      Float :lat
      Float :lon
      String :place_types_json, null: false, default: "[]"
      String :time_periods_json, null: false, default: "[]"
      Integer :position, null: false

      index :position
    end

    create_table(:place_index_names) do
      String :pleiades_id, null: false
      String :name_key, null: false

      index %i[pleiades_id name_key], unique: true
      index :name_key
    end
  end

  down do
    drop_table(:place_index_names)
    drop_table(:place_index)
  end
end
