# frozen_string_literal: true

require "yaml"
require "date"

module Nabu
  module Ops
    # The site's single-source-of-truth projection (P58 rider, owner
    # commission): every registry-derivable fact a site page cites lives in
    # site/_data/*.yml, GENERATED here, and the pages read it through
    # Liquid — so a new research desk or a fresh census appears everywhere
    # by regeneration, never by chasing prose. (The AxisPages stance one
    # level up: pages loop over data; hand-written text carries only what
    # no registry knows.)
    #
    # Two files, two natures:
    #
    #   * desks.yml — PURE registry projection (config/axes.yml order,
    #     persona split into name/blurb at the em-dash, public member
    #     counts). Deterministic from the registries alone — the drift
    #     guard (test/site/site_data_test.rb) regenerates it in memory and
    #     fails the suite the day the committed copy goes stale.
    #   * census.yml — LIVE catalog/fulltext numbers, stamped as_of. Dated
    #     by nature, refreshed at every gate (site/MAINTENANCE.md duty 1);
    #     the guard pins its SHAPE, never its dated values.
    class SiteData
      DESKS_FILE = "desks.yml"
      CENSUS_FILE = "census.yml"

      GENERATED_NOTE = "GENERATED by `rake site:data` (Nabu::Ops::SiteData) — do not hand-edit; " \
                       "regenerate at every gate."

      def initialize(registry:, data_dir:, catalog_path: nil, fulltext_path: nil, as_of: Date.today)
        @registry = registry
        @data_dir = data_dir
        @catalog_path = catalog_path
        @fulltext_path = fulltext_path
        @as_of = as_of
      end

      # The registry projection, as plain data (the drift guard compares
      # this against the committed file).
      def desks
        @registry.axes.each_axis.map do |axis|
          name, blurb = split_persona(axis.persona)
          { "slug" => axis.name, "persona" => name, "blurb" => blurb,
            "members" => @registry.public_axis_members(axis.name).size }
        end
      end

      # The live numbers the site's prose cites. Catalog required;
      # fulltext required too (the publishing box has both — a worktree
      # run points env overrides at the main checkout, the site:axes
      # pattern).
      def census
        catalog = Store.connect(@catalog_path, readonly: true)
        fulltext = Store.connect(@fulltext_path, readonly: true)
        live_docs = catalog[:documents].where(Sequel[:documents][:withdrawn] => false)
        languages = live_docs.exclude(Sequel[:documents][:language] => nil).distinct.select(:language).count
        top = live_docs.exclude(Sequel[:documents][:language] => nil)
                       .join(:passages, document_id: :id).where(Sequel[:passages][:withdrawn] => false)
                       .group(Sequel[:documents][:language])
                       .select { [documents[:language].as(:language), count.function.*.as(:passages)] }
                       .order(Sequel.desc(:passages)).limit(5).all
        tiers = fulltext[:passage_lemmas].group_and_count(:tier).as_hash(:tier, :count)
        documents = live_docs.count
        passages = catalog[:passages].where(withdrawn: false).count
        entries = catalog[:dictionary_entries].where(withdrawn: false).count
        {
          # Liquid cannot comma- or million-format, so every number the
          # prose cites ships BOTH raw and display-ready.
          "as_of" => @as_of.strftime("%-d %B %Y"),
          "documents" => documents, "documents_display" => self.class.commas(documents),
          "passages" => passages, "passages_display" => self.class.commas(passages),
          "language_codes" => languages,
          "top_languages" => top.map do |row|
            { "code" => row[:language], "passages" => row[:passages],
              "millions" => self.class.millions(row[:passages]) }
          end,
          "dictionary_entries" => entries, "dictionary_entries_display" => self.class.commas(entries),
          "dictionary_shelves" => catalog[:dictionaries].count,
          "gold_lemmas_m" => self.class.millions(tiers["gold"].to_i),
          "silver_lemmas_m" => self.class.millions(tiers["silver"].to_i),
          "gold_languages" => fulltext[:reflex_root_stats].count,
          "desks" => @registry.axes.size
        }
      ensure
        catalog&.disconnect
        fulltext&.disconnect
      end

      def self.commas(number)
        number.to_s.gsub(/(\d)(?=(\d{3})+\z)/, '\1,')
      end

      def self.millions(number)
        (number / 1_000_000.0).round(1).to_s
      end

      # Write both files. Returns the paths written.
      def generate!
        FileUtils.mkdir_p(@data_dir)
        [write(DESKS_FILE, desks), write(CENSUS_FILE, census)]
      end

      def self.split_persona(persona)
        name, blurb = persona.split(/\s+[—–]\s+/, 2)
        [name.to_s.strip, blurb.to_s.strip.sub(/\.\z/, "")]
      end

      private

      def split_persona(persona) = self.class.split_persona(persona)

      def write(name, data)
        path = File.join(@data_dir, name)
        File.write(path, "# #{GENERATED_NOTE}\n#{YAML.dump(data)}")
        path
      end
    end
  end
end
